#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Tue Oct 31 19:41:44 2017

@author: vishwas
"""

import pandas as pd

df1 = pd.read_csv("raw_data/Beer_review_data/beerreview1_13.csv", sep = ',')
df2 = pd.read_csv("raw_data/Beer_review_data/beerreview14_26.csv", sep = ',')
df3 = pd.read_csv("raw_data/Beer_review_data/beerreview27_39.csv", sep = ',')
df4 = pd.read_csv("raw_data/Beer_review_data/beerreview40_51.csv", sep = ',')

beer_rating = pd.concat([df1, df2, df3, df4], ignore_index = True)

# Only user_name, user_rating, and beer_name
beer_rating = beer_rating[["user_name", "user_rating", "beer_name"]]

# Writing a new csv file for colloborative filtering

beer_rating.to_csv("beer_ratings.csv", index = False)

beer_rating["beer_name"].isnull().sum()

